services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tickets_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      start_period: 10s  # 10 секунд на первый запуск ДО начала проверок
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s      # Проверять каждые 10 секунд
      timeout: 5s        # Таймаут самой проверки
      retries: 10        # 10 попыток

  bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    volumes:
      - ./src:/app/src
      - ./cache:/app/cache
      - ./.env:/app/.env
      - ./assets:/app/assets
    restart: unless-stopped

volumes:
  db_data:
  tickets_generated:
  stats_exports:
  cache:
