name: python CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 17904
          script: |
            cd ~/belekker
            # Обновляем локальную ветку, разрешая fast-forward только
            git fetch origin main
            git reset --hard origin/main
            # Проверим статус
            git status
            # Перезапуск Docker
            docker-compose down
            docker-compose up --build -d
